api_platform:
    title: 'Hello API Platform'
    version: '1.0.0'
    defaults:
        stateless: false
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        pagination_items_per_page: 10
        pagination_maximum_items_per_page: 50
    enable_docs: true
    enable_swagger_ui: true
    enable_re_doc: true
    description: 'Smoobu 2.0 API'
    formats:
        json:
            mime_types: ['application/json']
        jsonld:
            mime_types: ['application/ld+json']
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header