controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login_check:
    path: /api/login

upload_apartment_image:
    path: /api/apartments/upload-image
    controller: App\Controller\UploadApartmentImageController
    methods: [POST]